### ISSUE TITLE
プレーヤーカラーを追加する

### ISSUE THREAD

**Issue by 128na** [128na/sve_analyzer#2]
要調査：色の指定は色一覧が定義されていて色IDを指定する形？

色IDは`player`オブジェクトに`color_id`プロパティとして追加する。
```
player = {
  id: 123,
  ...
  color_id: xxx
}
```

**Comment by shingoushori** [comment]
相談です
プレーヤーカラーとしては、もう１色とセットのようです (基調色 + 補助色)
そして、シムトランスのソースコード player/simplay.h class player_t の変数としては
 uint8 player_color_1, player_color_2; となっています
補助色の方も入れられるように、プロパティの仕様を拡張することを提案します。
ご検討よろしくお願いします。

**Comment by 128na** [comment]
提案ありがとうございます。
では以下のように変更しましょう。

`player`オブジェクトに基本色は`color_1`、補助色は`color_2`プロパティとして追加する。
```
player = {
  id: 123,
  ...
  color_1: (int)xxx,
  color_2: (int)yyy
}
```

**Comment by shingoushori** [comment]
プルリク投げました #4 
ご確認よろしくお願いします。

色ID から RGB に変換するものも検討中です。

**Comment by 128na** [comment]
ありがとうございます。マージしました。

> 色ID から RGB に変換

色配列の定義が見つからなかったのでスクショから色を取得したものを追加してあります。
変換できるとありがたいです。
https://github.com/128na/sve_analyzer/blob/master/src/const.js#L64

**Comment by 128na** [comment]
色テーブル追加済み
